algoritmo "calculo peça"
// Função : solicitar valor da peça comprada e quantidade comprada  e valor total
// Autor : Laura Oliveira
// Data : 26/04/2022
// Seção de Declarações

 
var

valor, qntde, total: real

inicio
// entrada

escreval (" Digite a quantidade de peças compradas:")
leia (qntde)
escreval (" Digite valor unítario de cada peça:")
leia (valor)

// processamento
total<- valor*qntde


// saida
 escreval(" O total da sua compra é:",total)

fimalgoritmo
