algoritmo "Dolar"
// Função : Converter o valor do dolar
// Autor : Laura Oliveira
// Data : 03/05/2022
// Seção de Declarações 


var

dolar,realbr,resultado:real

inicio
// entrada

escreval("Digite a cotação do dolar hoje")
leia(dolar)
escreval("Digite o valor  em real a ser convertido")
leia(realbr)

//processamento

resultado<-(realbr/dolar)

//saida

escreval("O valor é:",resultado)


fimalgoritmo
