algoritmo "estoque medio"
// Função : Calcular o estoque medio de uma peça
// Autor : Laura Oliveira
// Data : 26/04/2022
// Seção de Declarações 


var

qntdemi , qntdema, estoquemedio:real

inicio
// entrada

escreval(" Digite quantidade máxima")
leia(qntdema)
escreval(" Digite quantidade mínima")
leia(qntdemi)

//processamento

estoquemedio<-(qntdema+qntdemi)/2

// saida

escreval("Seu estoque medio é:",estoquemedio)


fimalgoritmo
