algoritmo "Minutos e horas"
// Função : converter minutos e horas
// Autor :  Laura Oliveira
// Data : 10/05/2022
// Seção de Declarações 



var

horas,min,seg,tempo:real

inicio
// entrada

escreval("Digite a hora ")
leia(horas)
escreval(" Digite os minutos")
leia(min)


//processamento
tempo<-(min/60)+horas


// saida

escreval(" O tempo em segundos",tempo)
fimalgoritmo
