Algoritmo "im_par"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : verifica se o numero e impar ou par
// Autor(a)    : Laura Olivira
// Data atual  : 26/07/2022
Var

numero:inteiro

Inicio

// entrada e processamento

escreval("Digite o número")
leia(numero)

 se (numero mod 2=0) entao
    escreval("Esse número é par")
 senao entao
   escreval("Esse número é impar")
 fimse


Fimalgoritmo