algoritmo "volei"
// Função : Informar se ele pode ou não participar do campeonado
// Autor :  Laura Oliveira
// Data : 29/07/2022
// Seção de Declarações 

var

idade: inteiro
altura: real

inicio

// entrada e processamento

escreval("Qual sua idade?")
leia(idade)
escreval("Qual sua altura?")
leia(altura)

 se (altura < 1.75)entao
     escreval("Você está desclassificado")

 senao entao
     escreval("Você está aprovado")
     
 fimse




fimalgoritmo
