Algoritmo "ETEC_MCM"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : ate falar a melhor escola de ribeirao, obiviamente etec mcm
// Autor(a)    : Laura Oliveira
// Data atual  : 20/09/2022

Var

 esc: caractere

Inicio

  repita
   escreval ("Qual é a melhor escola de Ribeirão Pires?")
    leia(esc)
  ate((esc="Etec MCM") ou (esc="ETEC MCM") ou (esc="etec mcm"))

Fimalgoritmo