Algoritmo "INICIAL_FINAL"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : numero inicial e final
// Autor(a)    : Laura Oliveira
// Data atual  : 06/09/2022

Var
num1,num2,cont: inteiro

Inicio
escreval("Digite o número inicial")
leia(num1)
escreval("digite o número final ")
leia(num2)

 para cont de num1 ate num2 faca
     escreval(cont)
 fimpara


Fimalgoritmo