Algoritmo "SOMA_NUMPRIMOS"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : soma numeros primos de 1 a 100
// Autor(a)    : Laura Oliveira
// Data atual  : 20/09/2022

Var

  soma: inteiro

Inicio

  soma <- 2+3+5+7+11+13+17+19+23+29+31+37+41+43+47+53+59+61+67+71+73+79+83+89+97
  escreval(" a soma dos números é igual à", soma)


Fimalgoritmo